/* Generated by undra-bindgen. Do not edit.
 *
 * The module is its header: SwiftPM builds a C target only when it has a source file, so this
 * is that file. `hello_core_undra_api` itself is the core's, linked into the app (`undra build`).
 */
#include "hello_core_undra.h"
