# Generated by undra_source (ADR-061): the TypeScript runtime, @undra/runtime, compiled from runtimes/ts/@undra/runtime.
load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@bazel_skylib//rules:write_file.bzl", "write_file")

package(default_visibility = ["//visibility:public"])

# The framework adapters (react, vue, solid, svelte) import their framework, which an application that uses one installs and
# which this package does not: they are not part of the Bazel package. The Vite plugin needs Node's types, and the browser Db
# worker imports the optional wa-sqlite. Everything the generated bindings and an app's core calls need is here.
_EXCLUDED = [
    "_runtime/src/react.ts",
    "_runtime/src/vue.ts",
    "_runtime/src/solid.ts",
    "_runtime/src/svelte.ts",
    "_runtime/src/vite.ts",
    "_runtime/src/db-worker.ts",
]

# The options of runtimes/ts/@undra/runtime/tsconfig.json and tsconfig.build.json.
ts_project(
    name = "compile",
    srcs = glob(
        ["_runtime/src/**/*.ts"],
        exclude = _EXCLUDED,
    ),
    declaration = True,
    out_dir = "dist",
    root_dir = "_runtime/src",
    tsconfig = {
        "compilerOptions": {
            "target": "ES2022",
            "module": "ESNext",
            "moduleResolution": "bundler",
            "lib": ["ES2022", "DOM", "DOM.AsyncIterable", "ESNext.Disposable"],
            "types": [],
            "strict": True,
            "noUncheckedIndexedAccess": True,
            "exactOptionalPropertyTypes": True,
            "noImplicitOverride": True,
            "noImplicitReturns": True,
            "noUnusedLocals": True,
            "noUnusedParameters": True,
            "noFallthroughCasesInSwitch": True,
            "verbatimModuleSyntax": True,
            "isolatedModules": True,
            "skipLibCheck": True,
            "stripInternal": True,
        },
    },
)

# The package manifest the Bazel-built package carries: the entries the compiled files provide.
write_file(
    name = "package_json",
    out = "package.json",
    content = [
        "{",
        "  \"name\": \"@undra/runtime\",",
        "  \"version\": \"1.2.0\",",
        "  \"type\": \"module\",",
        "  \"sideEffects\": false,",
        "  \"exports\": {",
        "    \".\": { \"types\": \"./dist/index.d.ts\", \"default\": \"./dist/index.js\" },",
        "    \"./wire\": { \"types\": \"./dist/wire/index.d.ts\", \"default\": \"./dist/wire/index.js\" },",
        "    \"./realtime\": { \"types\": \"./dist/realtime.d.ts\", \"default\": \"./dist/realtime.js\" },",
        "    \"./db\": { \"types\": \"./dist/db.d.ts\", \"default\": \"./dist/db.js\" },",
        "    \"./worker\": { \"types\": \"./dist/worker.d.ts\", \"default\": \"./dist/worker.js\" }",
        "  },",
        "  \"main\": \"./dist/index.js\",",
        "  \"types\": \"./dist/index.d.ts\"",
        "}",
    ],
)

npm_package(
    name = "runtime",
    srcs = [
        ":compile",
        ":package_json",
    ],
    package = "@undra/runtime",
    version = "1.2.0",
)
