# Generated by undra-bindgen: R8 rules of the Undra core `hello_core`. Do not edit.
# Its JNI_OnLoad registers the natives of this class by name (ADR-044): keep both.
-keep class dev.undra.bazel.hello.UndraCoreNative {
    native <methods>;
}
