// Generated by undra-bindgen from the Undra schema of `hello-core` (schema hash 0xce5731fc471dc5b8). Do not edit.
@file:Suppress("ALL", "ktlint")

package dev.undra.bazel.hello

import dev.undra.runtime.UndraException
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException

sealed class TodoError(message: String) : UndraException(message) {
    data object EmptyTitle : TodoError("the title cannot be empty")

    companion object : UndraCodec<TodoError> {
        override fun encode(w: UndraWriter, v: TodoError) {
            when (v) {
                EmptyTitle -> w.writeU16(0u)
            }
        }

        override fun decode(r: UndraReader): TodoError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> EmptyTitle
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "TodoError")
            }
        }
    }
}
