// Generated by undra-bindgen from the Undra schema of `hello-core` (schema hash 0xce5731fc471dc5b8). Do not edit.
@file:Suppress("ALL", "ktlint")

package dev.undra.bazel.hello

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0xce5731fc471dc5b8uL
    const val NAMESPACE: String = "hello_core"

    object Objects {
        object Todos {
            const val TYPE_ID: UInt = 0xf5e31faau
            const val NEW: UInt = 0x35935deau
            const val ADD: UInt = 0xd13d7ad7u
            const val CLEAR_DONE: UInt = 0x27ffa842u
            const val SET_FILTER: UInt = 0x07781993u
            const val TOGGLE: UInt = 0x1cc45d38u
        }
    }

    object Functions {
        const val GREETING: UInt = 0xda6bbde2u
    }

    object Ports {}

    object Queries {}
}
