// Generated by undra-bindgen from the Undra schema of `hello-core` (schema hash 0x249f265dff3e0900). Do not edit.
@file:Suppress("ALL", "ktlint")

package dev.undra.bazel.hello

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.decodeAll

/** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
fun crashForSymbolsTest(reason: String, ctx: UndraCore = UndraHelloCore.core): UInt {
    val w = UndraWriter()
    w.writeStr(reason)
    try {
        val body = ctx.callSync(
            CallTarget.FreeFunction(UndraIds.Functions.CRASH_FOR_SYMBOLS_TEST),
            UndraIds.Functions.CRASH_FOR_SYMBOLS_TEST,
            w.toByteArray(),
        )
        return Codecs.u32.decodeAll(body)
    } catch (e: Exception) {
        throw UndraCallError.mapped(e)
    }
}

/** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
fun greeting(name: String, ctx: UndraCore = UndraHelloCore.core): String {
    val w = UndraWriter()
    w.writeStr(name)
    try {
        val body = ctx.callSync(
            CallTarget.FreeFunction(UndraIds.Functions.GREETING),
            UndraIds.Functions.GREETING,
            w.toByteArray(),
        )
        return Codecs.string.decodeAll(body)
    } catch (e: Exception) {
        throw UndraCallError.mapped(e)
    }
}
