// Generated by undra-bindgen from the Undra schema of `hello-core` (schema hash 0x249f265dff3e0900). Do not edit.
@file:Suppress("ALL", "ktlint")

package dev.undra.bazel.hello

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraStore
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.KeyedPatch
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.Payloads.ChangeOp
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException
import dev.undra.runtime.wire.decodeAll
import java.util.UUID
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

class Todos internal constructor(core: UndraCore, handle: Long) : UndraStore(core, handle) {
    private val _todos: MutableStateFlow<List<Todo>> = signal(emptyList())
    val todos: StateFlow<List<Todo>> = _todos.asStateFlow()
    private val _filter: MutableStateFlow<Filter> = signal(Filter.ALL)
    val filter: StateFlow<Filter> = _filter.asStateFlow()
    private val _visible: MutableStateFlow<List<Todo>> = signal(emptyList())
    /** Computed by the core; read-only. */
    val visible: StateFlow<List<Todo>> = _visible.asStateFlow()
    private val _remaining: MutableStateFlow<UInt> = signal(0u)
    /** Computed by the core; read-only. */
    val remaining: StateFlow<UInt> = _remaining.asStateFlow()

    /**
     * @throws TodoError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun add(title: String): Todo {
        val w = UndraWriter()
        w.writeStr(title)
        try {
            val body = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Todos.ADD),
                UndraIds.Objects.Todos.ADD,
                w.toByteArray(),
            )
            return Todo.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, TodoError)
        }
    }

    /** A failure is logged and passed to `LoadOptions.onError`; the method does not throw. */
    fun clearDone() {
        try {
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Todos.CLEAR_DONE),
                UndraIds.Objects.Todos.CLEAR_DONE,
                ByteArray(0),
            )
        } catch (e: Exception) {
            this.core.report(e, "Todos.clearDone")
        }
    }

    /** A failure is logged and passed to `LoadOptions.onError`; the method does not throw. */
    fun setFilter(filter: Filter) {
        try {
            val w = UndraWriter()
            Filter.encode(w, filter)
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Todos.SET_FILTER),
                UndraIds.Objects.Todos.SET_FILTER,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            this.core.report(e, "Todos.setFilter")
        }
    }

    /** A failure is logged and passed to `LoadOptions.onError`; the method does not throw. */
    fun toggle(id: UUID) {
        try {
            val w = UndraWriter()
            Codecs.uuid.encode(w, id)
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Todos.TOGGLE),
                UndraIds.Objects.Todos.TOGGLE,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            this.core.report(e, "Todos.toggle")
        }
    }

    override fun apply(signalId: UInt, op: ChangeOp, reader: UndraReader) {
        try {
            when (signalId) {
                0u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecVecTodo.decode(reader)
                        reader.finish()
                        _todos.value = value
                    } else if (op == ChangeOp.PATCH) {
                        val ops = KeyedPatch.decodePatch(reader, Todo)
                        reader.finish()
                        try {
                            _todos.value = KeyedPatch.applyPatch(_todos.value, ops)
                        } catch (e: WireException.PatchOutOfBounds) {
                            resync(0u)
                        }
                    }
                }
                1u -> {
                    if (op == ChangeOp.FULL) {
                        val value = Filter.decode(reader)
                        reader.finish()
                        _filter.value = value
                    }
                }
                2u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecVecTodo.decode(reader)
                        reader.finish()
                        _visible.value = value
                    }
                }
                3u -> {
                    if (op == ChangeOp.FULL) {
                        val value = Codecs.u32.decode(reader)
                        reader.finish()
                        _remaining.value = value
                    }
                }
                else -> Unit
            }
        } catch (e: Exception) {
            core.report(e, "Todos.apply(signal: $signalId)")
        }
    }

    /** Re-observes a signal whose mirror diverged from the core, to receive a full value. */
    private fun resync(signalId: UInt) {
        core.observe(handle, signalId, false)
        core.observe(handle, signalId, true)
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        operator fun invoke(ctx: UndraCore = UndraHelloCore.core): Todos = create(ctx)

        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(ctx: UndraCore = UndraHelloCore.core): Todos {
            val handle = ctx.constructObject(UndraIds.Objects.Todos.TYPE_ID, UndraIds.Objects.Todos.NEW, ByteArray(0))
            return ctx.adopt(handle, ::Todos)
        }
    }
}

private val codecVecTodo = Codecs.vec(Todo)
