// Generated by undra-bindgen from the Undra schema of `hello-core` (schema hash 0xce5731fc471dc5b8). Do not edit.
@file:Suppress("ALL", "ktlint")

package dev.undra.bazel.hello

import dev.undra.runtime.UndraEnum
import dev.undra.runtime.UndraRecord
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException
import java.util.UUID

data class Todo(
    val id: UUID,
    val title: String,
    val done: Boolean,
) : UndraRecord {
    companion object : UndraCodec<Todo> {
        override fun encode(w: UndraWriter, v: Todo) {
            Codecs.uuid.encode(w, v.id)
            w.writeStr(v.title)
            w.writeBool(v.done)
        }

        override fun decode(r: UndraReader): Todo = Todo(
            id = Codecs.uuid.decode(r),
            title = r.readStr(),
            done = r.readBool(),
        )
    }
}

enum class Filter(val index: UShort) : UndraEnum {
    ALL(0u),
    ACTIVE(1u),
    DONE(2u);

    companion object : UndraCodec<Filter> {
        override fun encode(w: UndraWriter, v: Filter) = w.writeU16(v.index)

        override fun decode(r: UndraReader): Filter {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> ALL
                1 -> ACTIVE
                2 -> DONE
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "Filter")
            }
        }
    }
}
