[workspace]
resolver = "3"
members = [
  "crates/undra-meta",
  "crates/undra-wire",
  "crates/undra-macros",
  "crates/undra-signals",
  "crates/undra-runtime",
  "crates/undra-ports",
  "crates/undra-testkit",
  "crates/undra-query",
  "crates/undra-ffi",
  "crates/undra-transport",
  "crates/undra-bindgen",
  "crates/undra-cli",
  "crates/undra",
  "examples/playground/core",
  "examples/cookbook/core",
  "examples/fieldbook/core",
  "examples/ios15-sample/core",
  "bench",
]

[workspace.package]
version = "1.0.0-rc.1"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/shreypdev/undra"
authors = ["Shrey <shreypdev@gmail.com>"]

[workspace.dependencies]
undra-meta = { path = "crates/undra-meta", version = "1.0.0-rc.1" }
undra-wire = { path = "crates/undra-wire", version = "1.0.0-rc.1" }
undra-macros = { path = "crates/undra-macros", version = "1.0.0-rc.1" }
undra-signals = { path = "crates/undra-signals", version = "1.0.0-rc.1" }
undra-runtime = { path = "crates/undra-runtime", version = "1.0.0-rc.1" }
undra-ports = { path = "crates/undra-ports", version = "1.0.0-rc.1" }
undra-testkit = { path = "crates/undra-testkit", version = "1.0.0-rc.1" }
undra-query = { path = "crates/undra-query", version = "1.0.0-rc.1" }
undra-ffi = { path = "crates/undra-ffi", version = "1.0.0-rc.1" }
undra-transport = { path = "crates/undra-transport", version = "1.0.0-rc.1" }
undra-bindgen = { path = "crates/undra-bindgen", version = "1.0.0-rc.1" }
undra = { path = "crates/undra", version = "1.0.0-rc.1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
inventory = "0.3"
parking_lot = "0.12"
slab = "0.4"
futures-core = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
pin-project-lite = "0.2"
proptest = "1"
criterion = { version = "0.5", default-features = false }
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
prettyplease = "0.2"
trybuild = "1"
heck = "0.5"
clap = { version = "4", features = ["derive"] }
libloading = "0.8"
notify = "7"
tungstenite = "0.24"
jni = "0.21"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "unwind"
strip = "symbols"
debug = false

[profile.release-wasm]
inherits = "release"
opt-level = "z"
panic = "abort"

[profile.bench]
inherits = "release"
debug = true
strip = "none"
