// Generated by `undra bindgen`: do not edit, it is rewritten with the bindings.
//
// ESLint 9's flat configuration is read from the directory ESLint runs in, never from a subdirectory, so the generated
// TypeScript cannot exclude itself. Spread this into your eslint.config.js, before your own entries (the path is wherever the
// bindings are; this file ignores the directory it is in, relative to where ESLint runs):
//
//     import undraGenerated from "./generated/ts/eslint.config.undra.mjs";
//     export default [...undraGenerated, /* your configuration */];
import { dirname, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const here = relative(process.cwd(), dirname(fileURLToPath(import.meta.url))).split(sep).join("/");

export default [{ ignores: [`${here}/**`] }];
