// swift-tools-version: 6.0
// Generated by `undra bindgen`: do not edit, it is rewritten with the bindings.
import PackageDescription

let package = Package(
    name: "HelloCore",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [.library(name: "HelloCore", targets: ["HelloCore"])],
    dependencies: [.package(url: "https://github.com/shreypdev/undra", from: "1.2.0")],
    targets: [
        // Declares the core's entry point; the core itself is linked into the app.
        .target(name: "HelloCoreFFI", path: "Sources/HelloCoreFFI"),
        .target(
            name: "HelloCore",
            dependencies: [
                "HelloCoreFFI",
                .product(name: "UndraRuntime", package: "undra"),
            ],
            path: "Sources/HelloCore"
        ),
    ],
    swiftLanguageModes: [.v6]
)
