// Generated by `undra bindgen`: do not edit, it is rewritten with the bindings.
//
// A plain JVM library (the bindings use no Android API). The Android project includes it
// as a module and depends on it; the runtime comes from a composite build of the Undra
// checkout or from the project's Undra release (ADR-063).
plugins {
    id("org.jetbrains.kotlin.jvm")
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11)
    }
}

dependencies {
    api("com.github.shreypdev.undra:runtime:v1.1.0")
}
