"""`undra_android_std`: the Rust standard library of the Android targets, pinned by checksum.

An Android core is a Cargo cross-build run by `undra build`: Cargo needs `rust-std` for each Android triple beside the host's
compiler, and the NDK (a declared input of `undra_core`, ADR-065) links it. The library is host independent, so one pin serves
every machine Bazel runs on. It comes from the same place `rules_rust` fetches it, `static.rust-lang.org`, and must be the
release of the application's `rust.toolchain(versions = [..])`: rustc refuses a standard library another release built.

Declared in the application's MODULE.bazel:

    undra.android_std(
        version = "1.99.0",
        sha256s = {
            "aarch64-linux-android": "<sha256 of rust-std-1.99.0-aarch64-linux-android.tar.xz>",
            "x86_64-linux-android": "<sha256 of rust-std-1.99.0-x86_64-linux-android.tar.xz>",
        },
    )

Why not `rust.toolchain(extra_target_triples = ["aarch64-linux-android", ..])`: that is a toolchain for an Android *platform*, which
Bazel resolves only with a C++ toolchain for that platform (`rules_android_ndk`), and the core is built in the host configuration.
"""

def _impl(rctx):
    version = rctx.attr.version
    lines = [
        "# Generated by undra_android_std.",
        'package(default_visibility = ["//visibility:public"])',
        "",
    ]
    names = []
    for triple, sha256 in sorted(rctx.attr.sha256s.items()):
        rctx.download_and_extract(
            url = "https://static.rust-lang.org/dist/rust-std-{v}-{t}.tar.xz".format(v = version, t = triple),
            sha256 = sha256,
            output = triple,
            stripPrefix = "rust-std-{v}-{t}/rust-std-{t}".format(v = version, t = triple),
        )
        names.append(triple)
        lines.append("""# The sysroot of {t}: `{t}/lib/rustlib/{t}/lib/*.rlib` and what rustc reads beside them.
filegroup(
    name = "{t}",
    srcs = glob(["{t}/lib/rustlib/**"]),
)
""".format(t = triple))
    lines.append("""# Every Android target's standard library.
filegroup(
    name = "std",
    srcs = [{}],
)""".format(", ".join(['":{}"'.format(n) for n in names])))
    rctx.file("BUILD.bazel", "\n".join(lines) + "\n")

undra_android_std = repository_rule(
    implementation = _impl,
    attrs = {
        "version": attr.string(doc = "The Rust release, as in `rust.toolchain(versions = [..])`."),
        "sha256s": attr.string_dict(doc = "The SHA-256 of `rust-std-<version>-<triple>.tar.xz`, by Rust target triple."),
    },
    doc = "The pinned `rust-std` of the Android targets (empty when the application declares none).",
)
