/* Generated by undra: do not edit.
 *
 * hello_core_undra.h: the entry point of the Undra core `hello_core` (C ABI version 2, docs/SPEC.md 6).
 * The core exports this one function. It returns the core's `UndraApi` table (declared by
 * undra.h), as `const void *` so that undra.h stays the one owner of that type.
 */
#ifndef HELLO_CORE_UNDRA_H
#define HELLO_CORE_UNDRA_H

#ifdef __cplusplus
extern "C" {
#endif

const void *hello_core_undra_api(void);

#ifdef __cplusplus
}
#endif

#endif /* HELLO_CORE_UNDRA_H */
