load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//visibility:public"])

exports_files([
    "android.bzl",
    "bindings.bzl",
    "bindings_test.bzl",
    "cli.bzl",
    "core.bzl",
    "defs.bzl",
    "kotlin.bzl",
    "swift.bzl",
    "ts.bzl",
])

bzl_library(
    name = "cli",
    srcs = ["cli.bzl"],
    deps = ["//undra/private:actions"],
)

bzl_library(
    name = "core",
    srcs = ["core.bzl"],
    deps = ["//undra/private:actions"],
)

bzl_library(
    name = "bindings",
    srcs = ["bindings.bzl"],
    deps = ["//undra/private:actions"],
)

bzl_library(
    name = "bindings_test",
    srcs = ["bindings_test.bzl"],
    deps = ["@bazel_lib//lib:write_source_files"],
)

bzl_library(
    name = "kotlin",
    srcs = ["kotlin.bzl"],
)

bzl_library(
    name = "ts",
    srcs = ["ts.bzl"],
)

bzl_library(
    name = "swift",
    srcs = ["swift.bzl"],
)

bzl_library(
    name = "defs",
    srcs = ["defs.bzl"],
    deps = [
        ":bindings",
        ":bindings_test",
        ":cli",
        ":core",
        ":kotlin",
        ":swift",
    ],
)
