//! The lint exclusions `undra bindgen` writes next to each generated tree (ADR-061).
//!
//! A repository that lints everything (ktlint, SwiftLint, ESLint, detekt) reports the generated bindings: they are the
//! output of a generator and have the generator's style, not the repository's. The fix is to tell each linter the tree
//! is generated, in the file each one reads, and to do it where the tree is, so it travels with it when an app copies
//! or publishes the tree on its own:
//!
//! | Tree | File | Read by |
//! |---|---|---|
//! | `kotlin/` | `.editorconfig` | ktlint and the IDE formatter, for every Kotlin file below it |
//! | `kotlin/**/*.kt` | `@file:Suppress("ALL", "ktlint")` (the Kotlin generator's header) | ktlint 1.x, detekt and IntelliJ, wherever the file is; not the compiler, whose warnings still show |
//! | `swift/` | `.swiftlint.yml` | SwiftLint: the `excluded:` list (the package's two source directories) to merge into the lint root's configuration |
//! | `ts/` | `.eslintrc.json` | ESLint 8 and earlier (`ignorePatterns`) |
//! | `ts/` | `eslint.config.undra.mjs` | ESLint 9's flat config: the entry to spread into `eslint.config.js`; it finds its own directory, so it is right wherever the tree is |
//!
//! No file names the directory the trees are written to: the same schema generates the same files into any directory (a test
//! compares two routes to the same bindings byte for byte), and a tree that is moved is still excluded. Every file is part of the
//! tree's manifest, so `undra bindgen --check` fails when one is missing or edited and a later
//! run removes it with the rest. `[bindings] lint_exclusions = "none"` in `undra.toml`
//! ([`crate::config::LintExclusions`]) writes none of these files, for a repository that configures its linters at the root;
//! the Kotlin `@file:Suppress` line is part of each Kotlin file and stays either way. The `.gitattributes` that collapses the trees in a review is another piece's
//! (ADR-062); nothing here conflicts with it.

use undra_bindgen::GeneratedFile;

use crate::config::Platform;

/// `kotlin/.editorconfig`.
pub const KOTLIN_EDITORCONFIG: &str = "\
# Generated by `undra bindgen`: do not edit, it is rewritten with the bindings.
#
# Keeps ktlint and the IDE's formatter out of the generated Kotlin: this module is the output of a generator, so its style
# is the generator's, not yours. Every generated file also starts with `@file:Suppress(\"ALL\", \"ktlint\")`, which
# ktlint 1.x, detekt and IntelliJ read without any configuration (the Kotlin compiler does not: its warnings still show).
#
# If your repository's own .editorconfig switches ktlint on for everything and you would rather say it once at the root,
# give the path of the bindings from that file's directory (a section with a slash is anchored there, so
# `[**/generated/**]` misses a `generated/` right beside the root .editorconfig):
#
#     [generated/**]
#     ktlint_standard = disabled
#     ktlint_experimental = disabled
#
# For the Gradle ktlint plugin (org.jlleitschuh.gradle.ktlint):
#
#     ktlint { filter { exclude { it.file.path.contains(\"/generated/\") } } }
#
# For detekt (detekt.yml):
#
#     build:
#       excludes: ['**/generated/**']

[*.{kt,kts}]
ktlint_standard = disabled
ktlint_experimental = disabled
ij_formatter_enabled = false
";

/// `swift/.swiftlint.yml`, for a package whose Swift module is `module` and whose C module is `ffi_module`.
#[must_use]
pub fn swiftlint(module: &str, ffi_module: &str) -> String {
    format!(
        "\
# Generated by `undra bindgen`: do not edit, it is rewritten with the bindings.
#
# Keeps SwiftLint out of the generated Swift package. SwiftLint reads `excluded:` from the configuration of the directory
# it runs in (a nested configuration's own `excluded:` is ignored), so put these lines in your repository's
# .swiftlint.yml, or merge this file into the run, wherever the package is:
#
#     swiftlint --config .swiftlint.yml --config <this file>
#
# The two directories are the package's: the generated Swift, and the C module that declares the core's entry point.
excluded:
  - \"**/Sources/{module}/Generated\"
  - \"**/Sources/{ffi_module}\"
"
    )
}

/// `ts/.eslintrc.json`: ESLint 8 and earlier read it from the tree (patterns are relative to the file).
pub const ESLINTRC: &str = "\
// Generated by `undra bindgen`: do not edit, it is rewritten with the bindings.
//
// Keeps ESLint (8 and earlier, eslintrc configuration) out of the generated TypeScript. ESLint 9's flat configuration is
// read only from the directory ESLint runs in: spread `eslint.config.undra.mjs`, next to this file, into your
// eslint.config.js.
{
  \"root\": false,
  \"ignorePatterns\": [\"**/*\"]
}
";

/// `ts/eslint.config.undra.mjs`.
pub const ESLINT_FLAT: &str = "\
// Generated by `undra bindgen`: do not edit, it is rewritten with the bindings.
//
// ESLint 9's flat configuration is read from the directory ESLint runs in, never from a subdirectory, so the generated
// TypeScript cannot exclude itself. Spread this into your eslint.config.js, before your own entries (the path is wherever the
// bindings are; this file ignores the directory it is in, relative to where ESLint runs):
//
//     import undraGenerated from \"./generated/ts/eslint.config.undra.mjs\";
//     export default [...undraGenerated, /* your configuration */];
import { dirname, relative, sep } from \"node:path\";
import { fileURLToPath } from \"node:url\";

const here = relative(process.cwd(), dirname(fileURLToPath(import.meta.url))).split(sep).join(\"/\");

export default [{ ignores: [`${here}/**`] }];
";

/// The lint files of the trees `platforms` generates, paths relative to the output directory. `module` and `ffi_module` are the
/// Swift package's two source directories.
#[must_use]
pub fn fragments(platforms: &[Platform], module: &str, ffi_module: &str) -> Vec<GeneratedFile> {
    let mut files = Vec::new();
    let mut add = |path: &str, contents: String| {
        files.push(GeneratedFile {
            path: path.to_owned(),
            contents,
        });
    };
    if platforms.contains(&Platform::Ios) {
        add("swift/.swiftlint.yml", swiftlint(module, ffi_module));
    }
    if platforms.contains(&Platform::Android) {
        add("kotlin/.editorconfig", KOTLIN_EDITORCONFIG.to_owned());
    }
    if platforms.contains(&Platform::Web) {
        add("ts/.eslintrc.json", ESLINTRC.to_owned());
        add("ts/eslint.config.undra.mjs", ESLINT_FLAT.to_owned());
    }
    files
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn each_tree_gets_the_file_its_linter_reads() {
        let paths = |platforms: &[Platform]| -> Vec<String> {
            fragments(platforms, "HelloCore", "HelloCoreFFI")
                .into_iter()
                .map(|f| f.path)
                .collect()
        };
        assert_eq!(paths(&[Platform::Android]), ["kotlin/.editorconfig"]);
        assert_eq!(paths(&[Platform::Ios]), ["swift/.swiftlint.yml"]);
        assert_eq!(
            paths(&[Platform::Web]),
            ["ts/.eslintrc.json", "ts/eslint.config.undra.mjs"]
        );
        assert_eq!(paths(&Platform::ALL).len(), 4);
        assert!(paths(&[]).is_empty());
    }

    #[test]
    fn the_editorconfig_disables_ktlint_for_kotlin_files_only() {
        let rules: Vec<&str> = KOTLIN_EDITORCONFIG
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .collect();
        assert_eq!(
            rules,
            [
                "[*.{kt,kts}]",
                "ktlint_standard = disabled",
                "ktlint_experimental = disabled",
                "ij_formatter_enabled = false",
            ],
            "the section is the one of the file's own tree, not `root = true`: a parent .editorconfig still applies to the rest"
        );
        assert!(
            !KOTLIN_EDITORCONFIG.contains("root = true"),
            "a nested file must not cut the search for the repository's own"
        );
    }

    #[test]
    fn the_root_section_the_editorconfig_suggests_matches_a_tree_beside_the_root_file() {
        // An EditorConfig section with a slash is anchored to its file's directory: ktlint 1.8 applies `[**/generated/**]` to
        // `app/generated/..` but not to `generated/..` beside the root .editorconfig, and reports every finding there.
        // `[generated/**]` is what the guide gives and the Bazel example's `lint_test` runs.
        assert!(
            KOTLIN_EDITORCONFIG
                .contains("#     [generated/**]\n#     ktlint_standard = disabled\n"),
            "{KOTLIN_EDITORCONFIG}"
        );
        assert!(
            !KOTLIN_EDITORCONFIG.contains("#     [**/"),
            "{KOTLIN_EDITORCONFIG}"
        );
    }

    #[test]
    fn nothing_names_the_directory_the_tree_is_written_to() {
        let yml = swiftlint("HelloCore", "HelloCoreFFI");
        assert!(
            yml.contains("excluded:\n  - \"**/Sources/HelloCore/Generated\"\n  - \"**/Sources/HelloCoreFFI\"\n"),
            "{yml}"
        );
        assert!(yml.contains("--config <this file>"), "{yml}");
        // The flat config finds its own directory, so it is right wherever the tree is.
        assert!(ESLINT_FLAT.contains("import.meta.url"));
        assert!(ESLINT_FLAT.contains("ignores: [`${here}/**`]"));
        for file in fragments(&Platform::ALL, "HelloCore", "HelloCoreFFI") {
            // (The Kotlin file's comment shows the repository-root form, `[generated/**]`, as an example.)
            let active: Vec<&str> = file
                .contents
                .lines()
                .filter(|l| !l.trim_start().starts_with('#') && !l.trim_start().starts_with("//"))
                .collect();
            assert!(
                active.iter().all(|l| !l.contains("generated")),
                "{} names a directory: the tree is not always called generated: {active:?}",
                file.path
            );
        }
    }

    #[test]
    fn the_eslintrc_is_valid_json_once_its_comments_are_gone() {
        let json: String = ESLINTRC
            .lines()
            .filter(|l| !l.trim_start().starts_with("//"))
            .collect::<Vec<_>>()
            .join("\n");
        let value: serde_json::Value = serde_json::from_str(&json).expect("JSON");
        assert_eq!(value["ignorePatterns"][0], "**/*");
        assert_eq!(value["root"], false);
        assert!(
            value
                .as_object()
                .unwrap()
                .keys()
                .all(|k| k == "root" || k == "ignorePatterns"),
            "ESLint rejects a configuration with a key it does not know: {value}"
        );
    }

    #[test]
    fn every_file_says_it_is_generated() {
        for file in fragments(&Platform::ALL, "HelloCore", "HelloCoreFFI") {
            assert!(
                file.contents
                    .contains("Generated by `undra bindgen`: do not edit"),
                "{} has no header",
                file.path
            );
        }
    }
}
