// Generated by undra-bindgen from the Undra schema of `hello-core` (schema hash 0xce5731fc471dc5b8). Do not edit.

import { UndraCore, UndraError, type AttachOptions, type LoadOptions, type Transport } from "@undra/runtime";
import { UndraIds } from "./ids.js";

/** The core `load` or `attach` gave this package, until it is closed. */
let loaded: UndraCore | null = null;
/** Set while `load` or `attach` is running, so a second one is refused. */
let starting = false;

function claim(): void {
  if (starting || (loaded !== null && !loaded.closed)) {
    throw new UndraError("state", "the core `hello_core` is already loaded: close it (core.close()) before loading it again");
  }
  starting = true;
}

async function started(start: Promise<UndraCore>): Promise<UndraCore> {
  try {
    loaded = await start;
    return loaded;
  } finally {
    starting = false;
  }
}

/**
 * The core these bindings belong to, `hello_core` (`[core] namespace` in undra.toml): `load` starts it,
 * and `core` is the core every generated class and function of this package uses unless it is given
 * another one.
 *
 * ```ts
 * await UndraHelloCore.load({ mode: "wasm-main", wasm: new URL("hello_core.wasm", import.meta.url) });
 * ```
 */
export const UndraHelloCore = {
  /** The core's namespace: its wasm module is `hello_core.wasm`, its native library `libhello_core`. */
  namespace: "hello_core",
  /** The schema hash these bindings were generated for. */
  schemaHash: UndraIds.schemaHash,

  /**
   * Loads the core (`UndraCore.load` with this package's schema hash and namespace) and makes it `core`. Rejects
   * with `UndraSchemaMismatchError` when the core was built from another schema, and with `UndraError` while
   * this core is already loaded. The default stores are kept under the namespace (`undra.<namespace>.kv`, ...).
   */
  async load(options: Omit<LoadOptions, "expectedSchemaHash" | "namespace">): Promise<UndraCore> {
    claim();
    return started(UndraCore.load({ ...options, expectedSchemaHash: UndraIds.schemaHash, namespace: UndraIds.namespace }));
  },

  /**
   * Attaches the core over a transport you provide (React Native's `NativeTransport`, a test double),
   * with this package's schema hash and namespace, and makes it `core`.
   */
  async attach(transport: Transport, options: Omit<AttachOptions, "expectedSchemaHash" | "namespace"> = {}): Promise<UndraCore> {
    claim();
    return started(UndraCore.attach(transport, { ...options, expectedSchemaHash: UndraIds.schemaHash, namespace: UndraIds.namespace }));
  },

  /**
   * The loaded core, or, while none is loaded (or after it was closed), the closed placeholder
   * `UndraCore.unloaded`, whose calls reject with `UndraCallError.Unavailable`.
   */
  get core(): UndraCore {
    return loaded !== null && !loaded.closed ? loaded : UndraCore.unloaded;
  },
};
