// Generated by undra-bindgen from the Undra schema of `hello-core` (schema hash 0xce5731fc471dc5b8). Do not edit.

import { type Codec, UndraError, WireError } from "@undra/runtime";

export type TodoErrorKind = "emptyTitle";

export abstract class TodoError extends UndraError {
  declare readonly kind: TodoErrorKind;
}

export namespace TodoError {
  export class EmptyTitle extends TodoError {
    declare readonly kind: "emptyTitle";

    constructor() {
      super("emptyTitle", "the title cannot be empty");
    }
  }
}

export const TodoErrorCodec: Codec<TodoError> = {
  encode(w, v) {
    if (v instanceof TodoError.EmptyTitle) {
      w.writeU16(0);
    } else {
      throw new TypeError(`unknown TodoError variant: ${v.kind}`);
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return new TodoError.EmptyTitle();
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "TodoError" });
    }
  },
};
