// Generated by undra-bindgen from the Undra schema of `hello-core` (schema hash 0x249f265dff3e0900). Do not edit.

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
export const UndraIds = {
  schemaHash: 0x249f265dff3e0900n,
  namespace: "hello_core",
  Objects: {
    Todos: {
      typeId: 0xf5e31faa,
      new: 0x35935dea,
      add: 0xd13d7ad7,
      clearDone: 0x27ffa842,
      setFilter: 0x07781993,
      toggle: 0x1cc45d38,
    },
  },
  Functions: {
    crashForSymbolsTest: 0x87d9758b,
    greeting: 0xda6bbde2,
  },
  Ports: {
  },
  Queries: {
  },
} as const;
