// Generated by undra-bindgen from the Undra schema of `hello-core` (schema hash 0x249f265dff3e0900). Do not edit.

import {
  CallTarget,
  UndraCallError,
  UndraCore,
  UndraWriter,
  codecs,
  decodeValue,
} from "@undra/runtime";
import { UndraHelloCore } from "./core.js";
import { UndraIds } from "./ids.js";

/** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
export async function crashForSymbolsTest(
  reason: string,
  core: UndraCore = UndraHelloCore.core,
): Promise<number> {
  const w = new UndraWriter();
  w.writeStr(reason);
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.crashForSymbolsTest,
      w.finish(),
    );
    return decodeValue(codecs.u32, body);
  } catch (error) {
    throw UndraCallError.mapped(error);
  }
}

/** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
export async function greeting(
  name: string,
  core: UndraCore = UndraHelloCore.core,
): Promise<string> {
  const w = new UndraWriter();
  w.writeStr(name);
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.greeting,
      w.finish(),
    );
    return decodeValue(codecs.string, body);
  } catch (error) {
    throw UndraCallError.mapped(error);
  }
}
