// Generated by undra-bindgen from the Undra schema of `hello-core` (schema hash 0x249f265dff3e0900). Do not edit.

import {
  CallTarget,
  ChangeOp,
  PatchError,
  Signal,
  UndraCallError,
  UndraCore,
  UndraReader,
  UndraStore,
  UndraWriter,
  adopt,
  applyPatch,
  codecs,
  decodePatch,
  decodeValue,
} from "@undra/runtime";
import { UndraHelloCore } from "./core.js";
import { TodoErrorCodec } from "./errors.js";
import { UndraIds } from "./ids.js";
import { type Filter, FilterCodec, type Todo, TodoCodec } from "./types.js";

export class Todos extends UndraStore {
  readonly todos: Signal<Todo[]> = new Signal<Todo[]>([]);
  readonly filter: Signal<Filter> = new Signal<Filter>("all");
  /** Computed by the core; read-only. */
  readonly visible: Signal<Todo[]> = new Signal<Todo[]>([]);
  /** Computed by the core; read-only. */
  readonly remaining: Signal<number> = new Signal<number>(0);

  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
    this._signals = [this.todos, this.filter, this.visible, this.remaining];
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(core: UndraCore = UndraHelloCore.core): Promise<Todos> {
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.Todos.typeId,
        UndraIds.Objects.Todos.new,
        new Uint8Array(0),
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    const store = adopt(core, handle, Todos);
    await store._observeAll();
    return store;
  }

  /**
   * @throws {TodoError}
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
   */
  async add(title: string, signal?: AbortSignal): Promise<Todo> {
    const w = new UndraWriter();
    w.writeStr(title);
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Todos.add,
        w.finish(),
        signal,
      );
      return decodeValue(TodoCodec, body);
    } catch (error) {
      throw UndraCallError.mapped(error, TodoErrorCodec);
    }
  }

  /** A failure is logged and passed to `onError`; the returned promise never rejects. */
  async clearDone(): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Todos.clearDone,
        new Uint8Array(0),
      );
    } catch (error) {
      this.core.report(error, "Todos.clearDone");
    }
  }

  /** A failure is logged and passed to `onError`; the returned promise never rejects. */
  async setFilter(filter: Filter): Promise<void> {
    try {
      const w = new UndraWriter();
      FilterCodec.encode(w, filter);
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Todos.setFilter,
        w.finish(),
      );
    } catch (error) {
      this.core.report(error, "Todos.setFilter");
    }
  }

  /** A failure is logged and passed to `onError`; the returned promise never rejects. */
  async toggle(id: string): Promise<void> {
    try {
      const w = new UndraWriter();
      w.writeUuid(id);
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Todos.toggle,
        w.finish(),
      );
    } catch (error) {
      this.core.report(error, "Todos.toggle");
    }
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    try {
      switch (signalId) {
        case 0:
          if (op === ChangeOp.FullValue) {
            this.todos._set(decodeValue(vecTodo, value));
          } else if (op === ChangeOp.KeyedPatch) {
            const r = new UndraReader(value);
            const ops = decodePatch(r, TodoCodec);
            r.finish();
            try {
              this.todos._set(applyPatch(this.todos.peek(), ops));
            } catch (error) {
              if (!(error instanceof PatchError)) throw error;
              this._resync(0);
            }
          }
          break;
        case 1:
          if (op === ChangeOp.FullValue) {
            this.filter._set(decodeValue(FilterCodec, value));
          }
          break;
        case 2:
          if (op === ChangeOp.FullValue) {
            this.visible._set(decodeValue(vecTodo, value));
          }
          break;
        case 3:
          if (op === ChangeOp.FullValue) {
            this.remaining._set(decodeValue(codecs.u32, value));
          }
          break;
        default:
          break;
      }
    } catch (error) {
      this.core.report(error, `Todos.apply(signal: ${signalId})`);
    }
  }

  /** Re-observes a signal whose mirror diverged from the core, to receive a full value. */
  private _resync(signalId: number): void {
    for (const on of [false, true]) {
      this.core.observe(this.handle, signalId, on).catch((error: unknown) => {
        this.core.report(error, `Todos.resync(signal: ${signalId})`);
      });
    }
  }
}

const vecTodo = codecs.vec(TodoCodec);
