// Generated by undra-bindgen from the Undra schema of `hello-core` (schema hash 0xce5731fc471dc5b8). Do not edit.

import { type Codec, WireError } from "@undra/runtime";

export interface Todo {
  id: string;
  title: string;
  done: boolean;
}

export const TodoCodec: Codec<Todo> = {
  encode(w, v) {
    w.writeUuid(v.id);
    w.writeStr(v.title);
    w.writeBool(v.done);
  },
  decode(r) {
    return {
      id: r.readUuid(),
      title: r.readStr(),
      done: r.readBool(),
    };
  },
};

export type Filter = "all" | "active" | "done";

export const FilterCodec: Codec<Filter> = {
  encode(w, v) {
    switch (v) {
      case "all":
        w.writeU16(0);
        break;
      case "active":
        w.writeU16(1);
        break;
      case "done":
        w.writeU16(2);
        break;
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return "all";
      case 1:
        return "active";
      case 2:
        return "done";
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "Filter" });
    }
  },
};
